services:

  book-service:
    image: alexmercer1234556789/book-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "4001:4001"
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - app-net

  club-service:
    image: alexmercer1234556789/club-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "4002:4002"
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - app-net

  event-service:
    image: alexmercer1234556789/club-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "4002:4002"
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - app-net

  gateway-service:
    image: alexmercer1234556789/gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      registry-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    networks:
      - app-net

  config-service:
    image: alexmercer1234556789/config-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8083/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      registry-service:
        condition: service_healthy
    networks:
      - app-net

  registry-service:
    image: alexmercer1234556789/registry-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8761:8761"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8761/eureka/apps || exit 1
      interval: 10s
      retries: 5
    networks:
      - app-net

networks:
  app-net:
    external: true