jwt:
    open-id-name: keycloak
    open-id-url: http://localhost:9090/realms/auth-server/.well-known/openid-configuration
    auth:
        converter:
            resource-id: gateway-service
            principle-attribute: preferred_username

server:
    port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    oauth:
      client-id: local-client-id-replace-with-client-secret
      client-secret: local-secret-replace-with-client-secret
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /user-service/v3/api-docs
        name: User Service

spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/auth-server
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: USER-SERVICE-SWAGGER
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs
  config:
    import: "configserver:${SPRING_CONFIG_URI:http://localhost:8083}"