logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE
management.endpoints.web.exposure.include=openapi, swagger-ui
JWT_ISSUER_URI=http://localhost:9090/realms/auth-server
JWT_RESOURCE_ID=gateway-service
