SPRING_CLOUD_CONFIG_URI=http://localhost:8083
OPEN_ID_HOST=localhost
KEYCLOAK_CLIENT_ID=interface-cli
KEYCLOAK_ADMIN_CLIENT_ID=service-cli
KEYCLOAK_CLIENT_SECRET=O4Qj8PBbCzvGhB5BoTB8W2IzRo2mB3Cv
KEYCLOAK_REALM=auth-server
KEYCLOAK_DOMAIN=http://localhost:9090